### ISSUE TITLE
Add documentation on how to work locally

### ISSUE THREAD

**Issue by Its-Alex** [spacefill/pgsql_holidays#8]
We use [`pgxn-tools`](https://github.com/pgxn/docker-pgxn-tools) to test this extension on CI.

We should add documentation in readme to explain how to work with it locally 🙏 

Why ?

Because I can test it locally:

```
➜  pgsql_holidays git:(add_github_action_tests) make all PROFILE="-Werror"
Makefile:31: /opt/homebrew/opt/libpq/lib/postgresql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/opt/homebrew/opt/libpq/lib/postgresql/pgxs/src/makefiles/pgxs.mk'.  Stop.
```

I miss [`pgxnclient`](https://pgxn.github.io/pgxnclient/), I think we can work within [a container]([`pgxn-tools`](https://github.com/pgxn/docker-pgxn-tools)) to prevent an error with different OS.

I think we can document:

- [ ] how to launch a container with [`pgxn-tools`](https://github.com/pgxn/docker-pgxn-tools) locally
- [ ] enter inside it
- [ ] launch postgres
- [ ] install the extension
- [ ] connect to postgres
- [ ] test that all is working fine

**Comment by Its-Alex** [comment]
cc @madtibo

**Comment by Its-Alex** [comment]
I think I need this issue to be done to review:

- https://github.com/spacefill/pgsql_holidays/pull/5
- https://github.com/spacefill/pgsql_holidays/pull/6

**Comment by madtibo** [comment]
thanks for the idea and the help to implement it @Its-Alex !
