### ISSUE TITLE
MacOS error on create_sql_file.sh

### ISSUE THREAD

**Issue by Its-Alex** [spacefill/pgsql_holidays#9]
When I try to run [`create_sql_file.sh`](https://github.com/spacefill/pgsql_holidays/blob/master/scripts/create_sql_file.sh), I have an error:

```
➜  pgsql_holidays git:(add_github_action_tests) ./scripts/create_sql_file.sh
sed: -I or -i may not be used with stdin
```

Problem came from `sed` from `BSD` under OSX and `sed` from `GNU` under `Linux`

@madtibo Can you fix it?

**Comment by madtibo** [comment]
@Its-Alex Is your issue fixed using [!11](https://github.com/spacefill/pgsql_holidays/pull/11)
